name: weather_app
description: A weather forecast app.

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Lato Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 500
    - family: Lato Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400