name: weather_app
description: A weather forecast app.

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^1.3.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.5
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Lato Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 500
    - family: Lato Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400