name: weather_app
description: A weather forecast app.

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^1.3.0
  dartz: ^0.10.1
  http: ^1.1.0
  flutter_mobx: ^2.0.6
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  google_fonts: ^4.0.3
  get_it: ^7.6.0
  geolocator: 10.0.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  translator: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mask_text_input_formatter: ^2.9.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/weatherapp.png"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/fonts/
    - assets/image/

  fonts:
    - family: Lato Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 500
    - family: Lato Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400